Algoritmo "entrada e saida de dados"
// Descrição   : Entrada e saida de dados
// Autor(a)    : Nome do(a) aluno(a)  Sandro Shayne Dutra
// Data atual  : 07/05/2020
Var
// Seção de Declarações das variáveis 
   nome: caractere
   nota: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval ("Seu Nome")
   leia(nome)
   escreval ("Sua Nota")
   leia(nota)
   
   escreval("nome digitado foi:", nome)
   escreval("A nota digitada foi:", nota)

Fimalgoritmo