Algoritmo "Variaveis"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a) Sandro Shayne Dutra
// Data atual  : 07/05/2020
Var
// Seção de Declarações das variáveis 
  primeiroNome, seugndoNome, cidade, endereco: caractere
  idade : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo